#! /bin/bash

# .chezmoiignore is respected by chezmoi managed already

# list of DIRECTORIES that are managed by chezmoi_managed
# but should not be expanded to tree
do_not_expand=(
  nvim
  .oh-my-zsh
)

# Convert do_not_expand to regex
filter=$(
  printf "|.*/?%s/?.*" "${do_not_expand[@]}" |
    cut -c 2-
)

# List of files managed by chezmoi
# without the directories that should not be expanded
chezmoi_managed="$(
  chezmoi managed |
    grep -Ev "$filter" |
    tree --fromfile --noreport |
    awk '!seen[$0]++'
)"
# Remove the leading dot from the files
chezmoi_managed=${chezmoi_managed/\./}

# Join the do_not_expand array to string
echo -n "Chezmoi Managed Directories without expansion: "
echo "${do_not_expand[*]}"
echo -n "Chezmoi Managed Files: "
echo "$chezmoi_managed"
