#!/bin/bash

list=(
  .config/color.palette
  .config/karabiner
  .config/bat
  .config/lf
  .config/nvim
  .config/wezterm
  .zsh
  .zshrc
  .zshenv
  .tmux.conf
  .tmux
  Library/Application\ Support/aichat
)

for item in "${list[@]}"; do
  chezmoi re-add "$HOME/$item"
done
