#!/bin/bash

#############################################
################ Key bindings ###############
#############################################
# @@ to execute last command
execute_last_command() {
  zle up-history
  zle accept-line
}
zle -N execute_last_command
bindkey '@@' execute_last_command
