
# █▀▄▀█ █▀█ █▄░█ █ ▀█▀ █▀█ █▀█ █▀
# █░▀░█ █▄█ █░▀█ █ ░█░ █▄█ █▀▄ ▄█


# Set your monitor configuration here
# See https://wiki.hyprland.org/Configuring/Monitors/

monitor=DP-2, 1920x1080@143, 0x0, 1
monitor=DP-1, 1920x1080@143, 1920x0, 1

workspace=1, monitor:DP-2, default:true
workspace=2, monitor:DP-1
