#! /bin/bash

function run_script() {
	if (($# < 1)); then
		echo "Usage: s <script_name>"
		return 1
	fi

	# get path of script
	local script_path
	script_path="$HOME/.desktop/scripts/$1"

	if [[ -d "$script_path" ]]; then
		echo "Path is pointing to a directory"
		return 1
	fi

	if [[ ! -e "$script_path" ]]; then
		echo "Script not found"
		return 1
	fi

	bash -c "$script_path"
}

alias s=run_script
