#!/bin/bash

function line() {
  width=$1

  if [[ $((width-2)) -le 0 ]]; then
    echo "line width too short"
    exit 1
  fi
  
  line=""
  # draw line
  for ((i=0; i<$((width-2)); i++)); do
    line+="-"
  done

  echo -n "+${line}+"
}

function color() {
  text="$1"

  if [ "$text" == "" ]; then
    echo "Usage: color text [color]"
    exit 1
  fi

  colors="$2"
  
  if [ -z "$2" ]; then
    echo -n "$text"
  else
    colors_end='\e[0m\033[K'
    echo -en "${colors}${text}${colors_end}"
  fi
}

function center() {
  pad(){
    padding=$1
    spaces=''
    for((i=0; i < padding; i++)); do
      spaces+='*'
    done
    echo -n "$spaces"
  }

  text="$1"
  padding="${2:-5}"
  spaces=$(pad "$padding")
  echo -n "${spaces}${text}${spaces}"
}

function wrap_message() {
  message_clear="$1"
  text="$2"
  padding="${3:-5}"
  wrap_color="$4"

  # when clearing message box, use default color if color is not set
  if [ -n "$message_clear" ] && [ -z "$wrap_color" ]; then
    wrap_color='\e[38;5;232;48;5;255m'
  fi

  # center text
  centered=$(center "$text" "$padding")

  # get border line
  width=$(echo -n "|$centered|" | wc -c) 
  border=" $(line "$width") "

  # when clearing message, go 4 cursors up
  if [ -n "$message_clear" ]; then
    echo -e "\033[4A"
    border="$(color "$border" "$wrap_color")"
  fi
  echo -e "$border"
  echo "$(color " |$centered| " "$wrap_color")" | tr '*' ' '
  echo -e "$border"
}
message_box() {
  wrap_message "" "$1" "$2" "$3"
}
message_box_clear() {
  wrap_message "clear" "$1" "$2" "$3"
}

#message_box "Remember to always quote your variables in Bash."
#message_box "hello world!"
#message_box "Welcome to the Bash scripting tutorial!"
#message_box "This is a test message."
#message_box "Goodbye!"
#echo ""
#message_box_clear "User settings have been reset."
#message_box_clear "Updating database records..."
#message_box_clear "System reboot required."
#message_box_clear "Installation complete."
#message_box_clear "Error: File not found."
